import { RequestFieldDefinition, RequestType } from "../types/RequestForm.types";

const tableStyle = 'width: 100%; border-collapse: collapse; font-family: "Segoe UI", Helvetica, Arial, sans-serif;';
const headerStyle = 'background-color: #001F3F; color: #ffffff; padding: 15px; text-align: left; border-radius: 8px 8px 0 0;';
const labelStyle = 'padding: 10px; border-bottom: 1px solid #f0f0f0; color: #666666; font-size: 12px; width: 30%; text-transform: uppercase; font-weight: bold;';
const valueStyle = 'padding: 10px; border-bottom: 1px solid #f0f0f0; color: #333333; font-size: 14px;';

const escapeHtml = (text: string): string => {
  const div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
};

const formatValue = (value: any): string => {
  if (Array.isArray(value)) {
    return value.length > 0 ? value.join(", ") : "---";
  }

  if (value === undefined || value === null || value === "") {
    return "---";
  }

  return String(value);
};
export const buildRequestEmailHtml = (
  selectedType: string,
  activeFields: any[],
  formData: Record<string, any>
): string => {
  const rows = activeFields
    .filter((field) => field.type !== "note")
    .map((field) => {
      const value = formData[field.name] || "—";
      const displayValue = String(value).replace(/\n/g, "<br/>");

      return `
        <tr>
          <td width="200" valign="top" style="padding: 12px 15px; font-family: 'Segoe UI', Arial, sans-serif; font-size: 12px; font-weight: 700; color: #334155; background-color: #f1f5f9; border-bottom: 1px solid #e2e8f0; border-right: 1px solid #e2e8f0; text-transform: uppercase; letter-spacing: 0.5px;">
            ${field.label}
          </td>
          <td valign="top" style="padding: 12px 15px; font-family: 'Segoe UI', Arial, sans-serif; font-size: 14px; color: #1e293b; border-bottom: 1px solid #e2e8f0; background-color: #ffffff; line-height: 1.5;">
            ${displayValue}
          </td>
        </tr>
      `;
    })
    .join("");

  return `
    <div style="background-color: #f8fafc; padding: 20px; font-family: 'Segoe UI', Arial, sans-serif;">
      
      <!-- Main Table Container -->
      <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width: 650px; margin: 0 auto; background-color: #ffffff; border: 1px solid #cbd5e1; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
        
        <!-- Premium Dark Header -->
        <tr>
          <td bgcolor="#1e293b" style="padding: 25px 30px; background-color: #1e293b;">
            <table cellpadding="0" cellspacing="0" border="0" width="100%">
              <tr>
                <td>
                  
                  <div style="font-size: 22px; font-weight: 700; color: #ffffff; margin-bottom: 5px;">
                    Legal Request Details
                  </div>
                  <div style="font-size: 14px; color: #94a3b8;">
                    Type: <span style="color: #ffffff; font-weight: 600;">${selectedType}</span>
                  </div>
                </td>
                <td align="right" valign="top">
                  <div style="font-size: 12px; color: #94a3b8; background: rgba(255,255,255,0.1); padding: 5px 10px; border-radius: 4px;">
                    ${new Date().toLocaleDateString('en-GB')}
                  </div>
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- Content Area -->
        <tr>
          <td style="padding: 30px;">
         

            <!-- Data Table with TH/TD look -->
            <table cellpadding="0" cellspacing="0" border="0" width="100%" style="border: 1px solid #e2e8f0; border-collapse: collapse;">
              <thead>
                <!-- Optional Table Header Row if needed -->
              </thead>
              <tbody>
                ${rows}
              </tbody>
            </table>

           
          </td>
        </tr>

       
      </table>

      <!-- Sub-footer info -->
      <div style="max-width: 650px; margin: 15px auto; text-align: center; font-size: 10px; color: #94a3b8; text-transform: uppercase; letter-spacing: 1px;">
        Generated by Streamline Add-In Taxonomy
      </div>
    </div>
  `;
};
// export const buildRequestEmailHtml = (
//   selectedType: RequestType,
//   activeFields: RequestFieldDefinition[],
//   formData: Record<string, any>
// ): string => {
//   const rows = activeFields
//     .filter((field) => field.type !== "note")
//     .map((field) => {
//       const displayValue = escapeHtml(formatValue(formData[field.name]));

//       return `
//         <tr>
//           <td style="${labelStyle}">${escapeHtml(field.label)}</td>
//           <td style="${valueStyle}">${displayValue}</td>
//         </tr>
//       `;
//     })
//     .join("");

//   return `
//     <div style="max-width: 600px; border: 1px solid #e0e0e0; border-radius: 8px;">
//       <div style="${headerStyle}">
//         <h2 style="margin: 0; font-size: 18px;">Legal Request: ${escapeHtml(selectedType)}</h2>
//         <p style="margin: 5px 0 0 0; font-size: 12px; opacity: 0.8;">Submitted on: ${new Date().toLocaleString()}</p>
//       </div>
//       <table style="${tableStyle}">
//         <tbody>
//           ${rows}
//         </tbody>
//       </table>
//       <div style="padding: 15px; background-color: #f9f9f9; border-radius: 0 0 8px 8px;">
//         <p style="margin: 0; font-size: 11px; color: #999;">
//           Please review the attached documents if mentioned in the fields above.
//         </p>
//       </div>
//     </div>
//     <br/>
//     <p style="color: #666; font-style: italic;">[Please attach any relevant files to this email before sending]</p>
//   `;
// };


// export const buildRequestEmailHtml = (
//   selectedType: RequestType,
//   activeFields: RequestFieldDefinition[],
//   formData: Record<string, any>
// ): string => {
//   const rows = activeFields
//     .filter((field) => field.type !== "note")
//     .map((field, index) => {
//       const displayValue = escapeHtml(formatValue(formData[field.name]));

//       return `
//         <tr style="
//           background-color: ${index % 2 === 0 ? "#ffffff" : "#f8fafc"};
//         ">
//           <td
//             valign="top"
//             style="
//               padding: 14px 16px;
//               width: 32%;
//               font-weight: 600;
//               font-size: 13px;
//               color: #374151;
//               border-bottom: 1px solid #e5e7eb;
//             "
//           >
//             ${escapeHtml(field.label)}
//           </td>

//           <td
//             valign="top"
//             style="
//               padding: 14px 16px;
//               font-size: 13px;
//               line-height: 1.6;
//               color: #111827;
//               border-bottom: 1px solid #e5e7eb;
//               word-break: break-word;
//             "
//           >
//             ${displayValue || "-"}
//           </td>
//         </tr>
//       `;
//     })
//     .join("");

//   return `
//   <div
//     style="
//       font-family: Arial, Helvetica, sans-serif;
//       background-color: #f3f4f6;
//       padding: 24px;
//     "
//   >

//     <div
//       style="
//         max-width: 760px;
//         margin: auto;
//         background: #ffffff;
//         border-radius: 12px;
//         overflow: hidden;
//         border: 1px solid #e5e7eb;
//       "
//     >

//       <!-- Header -->
//       <div
//         style="
//           background: linear-gradient(135deg, #1e3a8a, #2563eb);
//           padding: 24px;
//           color: white;
//         "
//       >
//         <div
//           style="
//             font-size: 20px;
//             font-weight: bold;
//             margin-bottom: 6px;
//           "
//         >
//           Legal Request Submission
//         </div>

//         <div
//           style="
//             font-size: 14px;
//             opacity: 0.92;
//           "
//         >
//           ${escapeHtml(selectedType)}
//         </div>

//         <div
//           style="
//             margin-top: 10px;
//             font-size: 12px;
//             opacity: 0.8;
//           "
//         >
//           Submitted on ${new Date().toLocaleString()}
//         </div>
//       </div>

//       <!-- Intro -->
//       <div
//         style="
//           padding: 22px 24px 10px 24px;
//           font-size: 14px;
//           color: #374151;
//           line-height: 1.7;
//         "
//       >
//         Please review the request details below.
//       </div>

//       <!-- Table -->
//       <div style="padding: 0 24px 24px 24px;">
//         <table
//           cellpadding="0"
//           cellspacing="0"
//           width="100%"
//           style="
//             border-collapse: collapse;
//             border: 1px solid #e5e7eb;
//             border-radius: 8px;
//             overflow: hidden;
//           "
//         >
//           <tbody>
//             ${rows}
//           </tbody>
//         </table>
//       </div>

//       <!-- Footer -->
//       <div
//         style="
//           background-color: #f9fafb;
//           padding: 18px 24px;
//           border-top: 1px solid #e5e7eb;
//         "
//       >
//         <div
//           style="
//             font-size: 12px;
//             color: #6b7280;
//             line-height: 1.6;
//           "
//         >
//           Please attach any supporting documents before sending this request.
//         </div>
//       </div>
//     </div>

//     <!-- Note -->
//     <div
//       style="
//         max-width: 760px;
//         margin: 14px auto 0 auto;
//         font-size: 12px;
//         color: #6b7280;
//         font-style: italic;
//         text-align: center;
//       "
//     >
//       Generated automatically by Legal Request Assistant
//     </div>

//   </div>
//   `;
// };